### ISSUE TITLE
css 垂直居中

### ISSUE THREAD

**Issue by wy-ei** [wy-ei/notebook#12]
### 单行文本，或者图片

容器高度固定，设置line-height 和 height 相同

### 内容高度确定

设置 top 为 50%，margin-top 为 负的高度的一半

### 内容高度不定，需要借助额外元素辅助

```html
<div class="wrap">
    <div class="content"></div>
    <div class="help"></div>
</div>
```

```css

.wrap {
    width: 500px;
    height: 500px;
    background-color: #ccc;
    text-align: center;
}

.content {
    display: inline-block;
    vertical-align: middle;
    height: 300px;
    width: 300px;
    background-color: yellow;
}
.help{
    display: inline-block;
    vertical-align: middle;
    height: 100%;
}
```

容器中一个辅助元素的高度设置为 100%，并且 vertical-align 都为 middle，这样另外一个元素就在容器中垂直居中了。

### 给出一样的 padding

把内容的上下内边距设为同样的值，这样就ok，很好理解

### 内容高度一定，设置其 top 和 bottom 为 0

居中的元素的高度一定要固定，否则会被拉伸。
